development:
  strategy: oauth
  oauth_consumer_key: 7CdYpMr1ShLddGg57zCgYg
  oauth_consumer_secret: UVWMO2A75Cdn0G1HZB9YPI4rV3cMkgMNK1GiFqvSX4
  base_url: "https://twitter.com"
  authorize_path: "/oauth/authenticate"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://vfac.dev:3000/tweets/oauth_callback"

test:
  strategy: oauth
  oauth_consumer_key: 7CdYpMr1ShLddGg57zCgYg
  oauth_consumer_secret: UVWMO2A75Cdn0G1HZB9YPI4rV3cMkgMNK1GiFqvSX4
  base_url: "https://twitter.com"
  authorize_path: "/oauth/authenticate"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://vfac.dev:3000/tweets/oauth_callback"

production:
  strategy: oauth
  oauth_consumer_key: 62OzszKNYOaMYL1s0ZOEpA
  oauth_consumer_secret: Mjp3TstboDvTYbJzIll4GThT9gj2BDJMtbtPJ5nYDw 
  authorize_path: "/oauth/authenticate"
  base_url: "https://twitter.com"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://www.voteforacure.com/tweets/oauth_callback"

